version: '3.4'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=lportal
      - MYSQL_ROOT_PASSWORD=secret
    #    volumes:
    #      - dbmysql:/var/lib/mysql
    command: --datadir=/var/lib/mysql/data --character-set-server=utf8 --collation-server=utf8_bin
  liferay-backup:
    image: liferay-backup
#    image: databack/mysql-backup
    depends_on:
      - mysql
    environment:
      - DB_SERVER=mysql
      - DB_USER=root
      - DB_PASS=secret
#      - DB_DUMP_TARGET=/portal_backup
#      - DB_RESTORE_TARGET=/portal_backup
#      - DB_DUMP_FILE_PREFIX=portal_backup
      - DB_SYNC_TARGET_DIR=/document_library
      - DB_NAMES=lportal
      - DB_DUMP_DEBUG=true
      - DB_DUMP_SAFECHARS=true
      - NICE=true
#      - DB_DUMP_CRON=0 2 * * *
#      - DB_DUMP_CRON=0 2 * * *
      - DB_DUMP_FREQ=1
      - DB_DUMP_BEGIN=+2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./portal_backup:/portal_backup
      - ./dl:/document_library
#  mysql-restore:
#    image: mysql-backup
#    environment:
#      - DB_SERVER=mysql
#      - DB_USER=root
#      - DB_PASS=secret
#      - DB_DUMP_DEBUG=true
#      - DB_RESTORE_TARGET=/db #/portal_bak.tgz
#      - DB_SYNC_TARGET_DIR=/include
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ./data:/db
#      - ./test:/include
